#!/usr/bin/env node
// Bundles data/*.json into src/data.js so the extension can import the taxonomy as a
// plain ES module — no JSON-import syntax to depend on, no runtime fetch of packaged
// files, and the engine keeps taking `data` as an argument exactly as the tests do.
//
// src/data.js is generated and gitignored. `npm run build` regenerates it.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { loadData } from './load-data.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const data = loadData();
const out = `// GENERATED by tools/build-data.mjs — do not edit. Source of truth is data/*.json.
export const DATA = ${JSON.stringify(data)};
`;
writeFileSync(join(ROOT, 'src', 'data.js'), out);
console.log(`src/data.js written (${(out.length / 1024).toFixed(1)} KB, taxonomy ${data.vocabularies.version})`);
